### ISSUE TITLE
Plugin does not seem to be working with Pimcore version 6.3.6

### ISSUE THREAD

**Issue by abernardgalilee** [elements-at/AlternateObjectTrees#11]
Hello all. 
When trying to install your plugin bundle, I get the following error : 
You have requested a non-existent service : "Elements\Bundle\AlternateObjectTreesBundle\Installer"
Any clue of what is going on?
Arnaud.

**Comment by fashxp** [comment]
hmm, works for me without any problems. are you on latest release?

**Comment by fashxp** [comment]
dev-master seems to be broken...
