### ISSUE TITLE
Bundle does not seem to be working with Pimcore version 6.5.x and 6.6.9

### ISSUE THREAD

**Issue by vmalyk** [elements-at/AlternateObjectTrees#18]
Hi!
Looks as bundle doesn't work on Pimcore 6.5 and it's related with changes  in  gridGetColumnConfigAction method and tree rendering.
Another issue is reproduced on Pimcore 6.6 and it'r related with https://github.com/pimcore/pimcore/pull/6146 and override admin actions. With enable I got the same issue as described in https://github.com/pimcore/pimcore/pull/6146#issuecomment-654135882. After disable AlternateObjectTrees, issue is gone.
Can you look?

Thnx!

**Comment by andreas-gruenwald** [comment]
I just merged the PR and created release 3.0.0, which is compatible with Pimcore V6.

**Comment by MaxMitter** [comment]
Updating to v3.0.0 leads to this error whenever I try to open any GridView.
![image](https://user-images.githubusercontent.com/53904763/90628920-bf069f80-e21e-11ea-8c9c-9d0ef2964164.png)

I managed to fix this by adding
```
options:
    expose: true
```
to _elements_alternate_object_trees in routing.yml as described [here](https://github.com/pimcore/pimcore/pull/6146#issuecomment-645261448)

**Comment by andreas-gruenwald** [comment]
> Updating to v3.0.0 leads to this error whenever I try to open any GridView.
> ![image](https://user-images.githubusercontent.com/53904763/90628920-bf069f80-e21e-11ea-8c9c-9d0ef2964164.png)
> 
> I managed to fix this by adding
> 
> ```
> options:
>     expose: true
> ```
> 
> to _elements_alternate_object_trees in routing.yml as described [here](https://github.com/pimcore/pimcore/pull/6146#issuecomment-645261448)
> 
> (Only tested with Pimcore v6.7.0+)

This is not related to the bundle, but it's related to your Pimcore Version (see #6146)
