### ISSUE TITLE
Attribute with value of '0' not filtered

### ISSUE THREAD

**Issue by butlersupply** [elements-at/AlternateObjectTrees#22]
In AdminController.php filterValues is not correct if the attribute value is '0', such as with a checkbox.  Add a test for this in function treeGetChildrenByIdAction() as below.

            $attributeValue = $request->get('attributeValue');
                foreach ($objects as &$object) {
                    if (!empty($attributeValue) || $attributeValue === '0') {    // test for '0'
                        $filterValues[$level] = $request->get('attributeValue');
                    }
                    $object['filterValues'] = $filterValues;
                }

**Comment by fashxp** [comment]
could you provide a PR for that too? thx.

**Comment by butlersupply** [comment]
Done
